import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { get, patch, post, put, remove, type Customer, type Lot, type Product, type User } from './api';
import { useAuth, useSafeMutation } from './auth';
import { Alert, Badge, DataTable, DateText, Empty, PageHeading, Panel, QueryState } from './ui';

const name = z.string().trim().min(1, 'Informe o nome').max(150);
const customerSchema = z.object({ name, document: z.string().max(30), contact: z.string().max(150) });
const productSchema = z.object({ name, code: z.string().max(80), description: z.string().max(500) });
const lotSchema = z.object({ code: z.string().trim().min(1, 'Informe o código').max(80), productId: z.string().min(1, 'Selecione o produto'), manufacturingDate: z.string(), expirationDate: z.string() }).refine(v => !v.manufacturingDate || !v.expirationDate || v.expirationDate >= v.manufacturingDate, { path: ['expirationDate'], message: 'A validade deve ser posterior à fabricação' });
const userSchema = z.object({ name: z.string().trim().min(1).max(100), email: z.email(), password: z.string().min(1, 'Informe a senha'), role: z.enum(['ADMIN', 'QUALITY_ANALYST', 'USER']) });
type CustomerForm = z.infer<typeof customerSchema>; type ProductForm = z.infer<typeof productSchema>; type LotForm = z.infer<typeof lotSchema>; type UserForm = z.infer<typeof userSchema>;

function Search({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <div className="filters"><input className="search" placeholder={`⌕  ${placeholder}`} value={value} onChange={e => onChange(e.target.value)} /></div>; }
function FormButtons({ cancel, saving }: { cancel: () => void; saving: boolean }) { return <div className="form-actions span-2"><button type="button" className="btn secondary" onClick={cancel}>Cancelar</button><button className="btn primary" type="submit" disabled={saving}>{saving ? 'Salvando…' : 'Salvar'}</button></div>; }

export function CustomersPage() {
  const { user } = useAuth(); const qc = useQueryClient(); const { data = [], isLoading, error } = useQuery({ queryKey: ['customers'], queryFn: () => get<Customer[]>('/customers') });
  const [query, setQuery] = useState(''); const [editing, setEditing] = useState<Customer | 'new' | null>(null); const [saving, setSaving] = useState(false); const mutation = useSafeMutation();
  const filtered = data.filter(c => `${c.name} ${c.document || ''} ${c.contact || ''}`.toLowerCase().includes(query.toLowerCase()));
  const deleteCustomer = async (record: Customer) => { if (!window.confirm(`Excluir ${record.name}?`)) return; await mutation.run(() => remove(`/customers/${record.id}`), () => qc.invalidateQueries({ queryKey: ['customers'] })); };
  return <><PageHeading section="OPERAÇÃO / CLIENTES" title="Clientes" subtitle="Cadastro de clientes" action={<button className="btn primary" onClick={() => setEditing('new')}>+ Adicionar</button>} />
    <Panel title="Lista de clientes" action={<span className="muted">{filtered.length} registros</span>}><Search value={query} onChange={setQuery} placeholder="Buscar cliente" /><QueryState loading={isLoading} error={error}>{filtered.length ? <DataTable headers={['NOME', 'DOCUMENTO', 'CONTATO', '']} rows={filtered.map(c => [c.name, c.document || '—', c.contact || '—', <div className="inline-actions"><button className="mini-btn accept" onClick={() => setEditing(c)}>Editar</button>{user?.role === 'ADMIN' && <button className="mini-btn reject" onClick={() => deleteCustomer(c)}>Excluir</button>}</div>])} /> : <Empty text="Nenhum cliente encontrado." />}</QueryState></Panel><Alert message={mutation.error} />
    {editing && <CustomerEditor key={editing === 'new' ? 'new' : editing.id} item={editing === 'new' ? undefined : editing} saving={saving} cancel={() => setEditing(null)} submit={async values => { setSaving(true); const result = await mutation.run(() => editing === 'new' ? post<Customer>('/customers', values) : put<Customer>(`/customers/${editing.id}`, values), () => { qc.invalidateQueries({ queryKey: ['customers'] }); setEditing(null); }); setSaving(false); return result; }} />}</>;
}
function CustomerEditor({ item, saving, cancel, submit }: { item?: Customer; saving: boolean; cancel: () => void; submit: (data: CustomerForm) => Promise<unknown> }) { const { register, handleSubmit, formState: { errors } } = useForm<CustomerForm>({ resolver: zodResolver(customerSchema), defaultValues: { name: item?.name || '', document: item?.document || '', contact: item?.contact || '' } }); return <Panel title={item ? 'Editar cliente' : 'Novo cliente'} className="editor-panel"><form className="form-grid" onSubmit={handleSubmit(submit)}><label>Nome<input {...register('name')} />{errors.name && <small className="error">{errors.name.message}</small>}</label><label>Documento<input {...register('document')} /></label><label>Contato<input {...register('contact')} /></label><FormButtons cancel={cancel} saving={saving} /></form></Panel>; }

export function ProductsPage() {
  const { user } = useAuth(); const qc = useQueryClient(); const { data = [], isLoading, error } = useQuery({ queryKey: ['products'], queryFn: () => get<Product[]>('/products') });
  const [query, setQuery] = useState(''); const [editing, setEditing] = useState<Product | 'new' | null>(null); const [saving, setSaving] = useState(false); const mutation = useSafeMutation();
  const filtered = data.filter(p => `${p.name} ${p.code || ''}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeading section="OPERAÇÃO / PRODUTOS" title="Produtos" subtitle="Catálogo de produtos" action={<button className="btn primary" onClick={() => setEditing('new')}>+ Novo</button>} /><Panel title="Lista de produtos" action={<span className="muted">{filtered.length} registros</span>}><Search value={query} onChange={setQuery} placeholder="Buscar produto" /><QueryState loading={isLoading} error={error}>{filtered.length ? <DataTable headers={['CÓDIGO', 'NOME', 'DESCRIÇÃO', '']} rows={filtered.map(p => [p.code || '—', p.name, p.description || '—', <div className="inline-actions"><button className="mini-btn accept" onClick={() => setEditing(p)}>Editar</button>{user?.role === 'ADMIN' && <button className="mini-btn reject" onClick={async () => { if (!window.confirm(`Excluir ${p.name}?`)) return; await mutation.run(() => remove(`/products/${p.id}`), () => qc.invalidateQueries({ queryKey: ['products'] })); }}>Excluir</button>}</div>])} /> : <Empty text="Nenhum produto encontrado." />}</QueryState></Panel><Alert message={mutation.error} />{editing && <ProductEditor key={editing === 'new' ? 'new' : editing.id} item={editing === 'new' ? undefined : editing} saving={saving} cancel={() => setEditing(null)} submit={async values => { setSaving(true); await mutation.run(() => editing === 'new' ? post<Product>('/products', values) : put<Product>(`/products/${editing.id}`, values), () => { qc.invalidateQueries({ queryKey: ['products'] }); setEditing(null); }); setSaving(false); }} />}</>;
}
function ProductEditor({ item, saving, cancel, submit }: { item?: Product; saving: boolean; cancel: () => void; submit: (data: ProductForm) => Promise<unknown> }) { const { register, handleSubmit, formState: { errors } } = useForm<ProductForm>({ resolver: zodResolver(productSchema), defaultValues: { name: item?.name || '', code: item?.code || '', description: item?.description || '' } }); return <Panel title={item ? 'Editar produto' : 'Novo produto'} className="editor-panel"><form className="form-grid" onSubmit={handleSubmit(submit)}><label>Nome<input {...register('name')} />{errors.name && <small className="error">{errors.name.message}</small>}</label><label>Código<input {...register('code')} /></label><label className="span-2">Descrição<textarea {...register('description')} rows={3} /></label><FormButtons cancel={cancel} saving={saving} /></form></Panel>; }

export function LotsPage() {
  const { user } = useAuth(); const qc = useQueryClient(); const lots = useQuery({ queryKey: ['lots'], queryFn: () => get<Lot[]>('/lots') }); const products = useQuery({ queryKey: ['products'], queryFn: () => get<Product[]>('/products') });
  const [query, setQuery] = useState(''); const [editing, setEditing] = useState<Lot | 'new' | null>(null); const [saving, setSaving] = useState(false); const mutation = useSafeMutation();
  const filtered = (lots.data || []).filter(l => `${l.code} ${l.productName}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeading section="OPERAÇÃO / LOTES" title="Lotes" subtitle="Rastreabilidade de produção" action={<button className="btn primary" onClick={() => setEditing('new')}>+ Novo</button>} /><Panel title="Lista de lotes" action={<span className="muted">{filtered.length} registros</span>}><Search value={query} onChange={setQuery} placeholder="Código ou produto" /><QueryState loading={lots.isLoading} error={lots.error}>{filtered.length ? <DataTable headers={['CÓDIGO', 'PRODUTO', 'FABRICAÇÃO', 'VALIDADE', '']} rows={filtered.map(l => [l.code, l.productName, <DateText value={l.manufacturingDate} />, <DateText value={l.expirationDate} />, <div className="inline-actions"><button className="mini-btn accept" onClick={() => setEditing(l)}>Editar</button>{user?.role === 'ADMIN' && <button className="mini-btn reject" onClick={async () => { if (!window.confirm(`Excluir ${l.code}?`)) return; await mutation.run(() => remove(`/lots/${l.id}`), () => qc.invalidateQueries({ queryKey: ['lots'] })); }}>Excluir</button>}</div>])} /> : <Empty text="Nenhum lote encontrado." />}</QueryState></Panel><Alert message={mutation.error} />{editing && <QueryState loading={products.isLoading} error={products.error}><LotEditor key={editing === 'new' ? 'new' : editing.id} item={editing === 'new' ? undefined : editing} products={products.data || []} saving={saving} cancel={() => setEditing(null)} submit={async values => { setSaving(true); const body = { ...values, manufacturingDate: values.manufacturingDate || null, expirationDate: values.expirationDate || null }; await mutation.run(() => editing === 'new' ? post<Lot>('/lots', body) : put<Lot>(`/lots/${editing.id}`, body), () => { qc.invalidateQueries({ queryKey: ['lots'] }); setEditing(null); }); setSaving(false); }} /></QueryState>}</>;
}
function LotEditor({ item, products, saving, cancel, submit }: { item?: Lot; products: Product[]; saving: boolean; cancel: () => void; submit: (data: LotForm) => Promise<unknown> }) { const { register, handleSubmit, formState: { errors } } = useForm<LotForm>({ resolver: zodResolver(lotSchema), defaultValues: { code: item?.code || '', productId: item?.productId || '', manufacturingDate: item?.manufacturingDate || '', expirationDate: item?.expirationDate || '' } }); return <Panel title={item ? 'Editar lote' : 'Novo lote'} className="editor-panel"><form className="form-grid" onSubmit={handleSubmit(submit)}><label>Código<input {...register('code')} />{errors.code && <small className="error">{errors.code.message}</small>}</label><label>Produto<select {...register('productId')}><option value="">Selecione</option>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select>{errors.productId && <small className="error">{errors.productId.message}</small>}</label><label>Fabricação<input type="date" {...register('manufacturingDate')} /></label><label>Validade<input type="date" {...register('expirationDate')} />{errors.expirationDate && <small className="error">{errors.expirationDate.message}</small>}</label><FormButtons cancel={cancel} saving={saving} /></form></Panel>; }

export function UsersPage() {
  const { user } = useAuth(); const qc = useQueryClient(); const users = useQuery({ queryKey: ['users'], queryFn: () => get<User[]>('/users') }); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const mutation = useSafeMutation();
  return <><PageHeading section="ADMINISTRAÇÃO / USUÁRIOS" title="Usuários" subtitle="Acesso e perfis" action={<button className="btn primary" onClick={() => setShowForm(true)}>+ Criar usuário</button>} /><Panel title="Usuários cadastrados"><QueryState loading={users.isLoading} error={users.error}>{users.data?.length ? <DataTable headers={['NOME', 'E-MAIL', 'PERFIL', 'STATUS', '']} rows={users.data.map(u => [u.name, u.email, u.role, <Badge tone={u.active ? 'teal' : 'gray'}>{u.active ? 'Ativo' : 'Inativo'}</Badge>, <button className="mini-btn accept" disabled={mutation.pending || (u.id === user?.id && u.active)} onClick={async () => { if (!window.confirm(`${u.active ? 'Desativar' : 'Ativar'} ${u.name}?`)) return; await mutation.run(() => patch<User>(`/users/${u.id}/active`, { active: !u.active }), () => qc.invalidateQueries({ queryKey: ['users'] })); }}>{u.active ? 'Desativar' : 'Ativar'}</button>])} /> : <Empty text="Nenhum usuário encontrado." />}</QueryState></Panel><Alert message={mutation.error} />{showForm && <UserEditor saving={saving} cancel={() => setShowForm(false)} submit={async values => { setSaving(true); await mutation.run(() => post<User>('/users', values), () => { qc.invalidateQueries({ queryKey: ['users'] }); setShowForm(false); }); setSaving(false); }} />}</>;
}
function UserEditor({ saving, cancel, submit }: { saving: boolean; cancel: () => void; submit: (data: UserForm) => Promise<unknown> }) { const { register, handleSubmit, formState: { errors } } = useForm<UserForm>({ resolver: zodResolver(userSchema), defaultValues: { name: '', email: '', password: '', role: 'USER' } }); return <Panel title="Criar usuário" className="editor-panel"><form className="form-grid" onSubmit={handleSubmit(submit)}><label>Nome<input {...register('name')} />{errors.name && <small className="error">Informe um nome válido.</small>}</label><label>E-mail<input type="email" {...register('email')} />{errors.email && <small className="error">Informe um e-mail válido.</small>}</label><label>Senha<input type="password" autoComplete="new-password" {...register('password')} />{errors.password && <small className="error">Informe a senha.</small>}</label><label>Perfil<select {...register('role')}><option value="USER">USER</option><option value="QUALITY_ANALYST">QUALITY_ANALYST</option><option value="ADMIN">ADMIN</option></select></label><FormButtons cancel={cancel} saving={saving} /></form></Panel>; }
