import { useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { complaintLabels, formatDate, get, post, put, type Complaint, type ComplaintStatus, type CorrectiveAction, type Customer, type Investigation, type Lot, type Product } from './api';
import { useAuth, useSafeMutation } from './auth';
import { Alert, Badge, DataTable, Empty, PageHeading, Panel, QueryState } from './ui';

export function ComplaintBadge({ status }: { status: ComplaintStatus }) { return <Badge tone={status === 'INVESTIGATING' ? 'blue' : status === 'UNDER_ANALYSIS' ? 'amber' : status === 'OPEN' ? 'teal' : 'gray'}>{complaintLabels[status]}</Badge>; }
export function ComplaintLink({ item, suffix = '' }: { item: Complaint; suffix?: string }) { return <Link className="row-link" to={`/reclamacoes/${item.id}${suffix}`}>{item.title}</Link>; }
function greetingByLocalTime() { const hour = new Date().getHours(); return hour < 5 || hour >= 18 ? 'Boa noite' : hour < 12 ? 'Bom dia' : 'Boa tarde'; }
export function Dashboard() {
  const { user } = useAuth(); const complaints = useQuery({ queryKey: ['complaints'], queryFn: () => get<Complaint[]>('/complaints') }); const investigations = useQuery({ queryKey: ['investigations'], queryFn: () => get<Investigation[]>('/investigations') }); const actions = useQuery({ queryKey: ['actions'], queryFn: () => get<CorrectiveAction[]>('/corrective-actions') });
  const all = complaints.data || []; const inv = investigations.data || []; const act = actions.data || [];
  return <><PageHeading section="VISÃO GERAL" title={`${greetingByLocalTime()}, ${user?.name.split(' ')[0] || ''}`} subtitle="Itens que precisam de acompanhamento" />
    <QueryState loading={complaints.isLoading || investigations.isLoading || actions.isLoading} error={complaints.error || investigations.error || actions.error}>
      <div className="metrics"><div className="metric"><span>RECLAMAÇÕES ABERTAS</span><strong>{all.filter(c => c.status !== 'RESOLVED' && c.status !== 'CLOSED').length}</strong><small>Em acompanhamento</small></div><div className="metric"><span>EM INVESTIGAÇÃO</span><strong>{inv.filter(i => i.status === 'IN_PROGRESS').length}</strong><small>Análise em andamento</small></div><div className="metric"><span>AÇÕES PENDENTES</span><strong>{act.filter(a => a.status === 'PENDING').length}</strong><small>Aguardando execução</small></div><div className="metric"><span>AGUARDAM INFORMAÇÃO</span><strong>{inv.filter(i => i.status === 'WAITING_INFORMATION').length}</strong><small>Pendente de retorno</small></div></div>
      <Panel title="Reclamações recentes" action={<Link className="text-link" to="/reclamacoes">Ver todas →</Link>}>{all.length ? <DataTable headers={['TÍTULO', 'CLIENTE', 'STATUS', 'DATA']} rows={[...all].sort((a,b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 6).map(c => [<ComplaintLink item={c} />, c.customerName, <ComplaintBadge status={c.status} />, formatDate(c.createdAt)])} /> : <Empty text="Nenhuma reclamação registrada." />}</Panel>
    </QueryState></>;
}
export function ComplaintsPage() {
  const { data = [], isLoading, error } = useQuery({ queryKey: ['complaints'], queryFn: () => get<Complaint[]>('/complaints') }); const [query, setQuery] = useState(''); const [status, setStatus] = useState('ALL');
  const filtered = useMemo(() => data.filter(c => `${c.title} ${c.customerName} ${c.lotCode || ''}`.toLowerCase().includes(query.toLowerCase()) && (status === 'ALL' || c.status === status)), [data, query, status]);
  return <><PageHeading section="OPERAÇÃO / RECLAMAÇÕES" title="Reclamações" subtitle="Registro, busca e acompanhamento dos casos" action={<Link className="btn primary" to="/reclamacoes/nova">+ Nova reclamação</Link>} /><Panel title="Todos os registros" action={<span className="muted">{filtered.length} registros</span>}><div className="filters"><input className="search" placeholder="⌕  Buscar por título, cliente ou lote" value={query} onChange={e => setQuery(e.target.value)} /><select value={status} onChange={e => setStatus(e.target.value)}><option value="ALL">Status: Todos</option>{Object.entries(complaintLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><QueryState loading={isLoading} error={error}>{filtered.length ? <DataTable headers={['TÍTULO', 'CLIENTE', 'PRODUTO', 'LOTE', 'STATUS', 'CRIADA']} rows={filtered.map(c => [<ComplaintLink item={c} />, c.customerName, c.productName, c.lotCode || '—', <ComplaintBadge status={c.status} />, formatDate(c.createdAt)])} /> : <Empty text="Nenhuma reclamação encontrada." />}</QueryState></Panel></>;
}
const complaintSchema = z.object({ title: z.string().trim().min(1, 'Informe o título').max(150), description: z.string().trim().min(1, 'Informe a descrição').max(3000), customerId: z.string().min(1, 'Selecione o cliente'), productId: z.string().min(1, 'Selecione o produto'), lotId: z.string() });
type ComplaintForm = z.infer<typeof complaintSchema>;
export function ComplaintFormPage({ edit = false }: { edit?: boolean }) {
  const { id = '' } = useParams(); const navigate = useNavigate(); const qc = useQueryClient(); const mutation = useSafeMutation(); const [saving, setSaving] = useState(false);
  const complaint = useQuery({ queryKey: ['complaint', id], queryFn: () => get<Complaint>(`/complaints/${id}`), enabled: edit });
  const customers = useQuery({ queryKey: ['customers'], queryFn: () => get<Customer[]>('/customers') }); const products = useQuery({ queryKey: ['products'], queryFn: () => get<Product[]>('/products') }); const lots = useQuery({ queryKey: ['lots'], queryFn: () => get<Lot[]>('/lots') });
  return <><PageHeading section={edit ? 'RECLAMAÇÕES / EDITAR' : 'RECLAMAÇÕES / NOVA RECLAMAÇÃO'} title={edit ? 'Editar reclamação' : 'Registrar reclamação'} subtitle="Dados iniciais para rastrear o caso" /><QueryState loading={(edit && complaint.isLoading) || customers.isLoading || products.isLoading || lots.isLoading} error={complaint.error || customers.error || products.error || lots.error}>{(!edit || complaint.data) && <ComplaintEditor key={complaint.data?.id || 'new'} item={complaint.data} customers={customers.data || []} products={products.data || []} lots={lots.data || []} saving={saving} submit={async values => { const lot = (lots.data || []).find(l => l.id === values.lotId); if (lot && lot.productId !== values.productId) return; setSaving(true); const body = { ...values, lotId: values.lotId || null }; await mutation.run(() => edit ? put<Complaint>(`/complaints/${id}`, body) : post<Complaint>('/complaints', body), result => { qc.invalidateQueries({ queryKey: ['complaints'] }); qc.invalidateQueries({ queryKey: ['complaint', result.id] }); navigate(`/reclamacoes/${result.id}`); }); setSaving(false); }} />}</QueryState><Alert message={mutation.error} /></>;
}
function ComplaintEditor({ item, customers, products, lots, saving, submit }: { item?: Complaint; customers: Customer[]; products: Product[]; lots: Lot[]; saving: boolean; submit: (values: ComplaintForm) => Promise<void> }) {
  const { register, handleSubmit, watch, setValue, formState: { errors } } = useForm<ComplaintForm>({ resolver: zodResolver(complaintSchema), defaultValues: { title: item?.title || '', description: item?.description || '', customerId: item?.customerId || '', productId: item?.productId || '', lotId: item?.lotId || '' } });
  const productId = watch('productId'); const selectedLot = watch('lotId'); const mismatch = !!selectedLot && !lots.some(l => l.id === selectedLot && l.productId === productId);
  return <Panel title="Informações da reclamação"><form className="form-grid" onSubmit={handleSubmit(submit)}><label className="span-2">Título<input {...register('title')} />{errors.title && <small className="error">{errors.title.message}</small>}</label><label className="span-2">Descrição<textarea {...register('description')} rows={5} />{errors.description && <small className="error">{errors.description.message}</small>}</label><label>Cliente<select {...register('customerId')}><option value="">Selecione o cliente</option>{customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select>{errors.customerId && <small className="error">{errors.customerId.message}</small>}</label><label>Produto<select {...register('productId')} onChange={e => { setValue('productId', e.target.value); setValue('lotId', ''); }}><option value="">Selecione o produto</option>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select>{errors.productId && <small className="error">{errors.productId.message}</small>}</label><label>Lote <span className="optional">(opcional)</span><select {...register('lotId')}><option value="">Sem lote</option>{lots.filter(l => l.productId === productId).map(l => <option key={l.id} value={l.id}>{l.code}</option>)}</select><small>Lotes relacionados ao produto selecionado</small>{mismatch && <small className="error">Selecione um lote do produto escolhido.</small>}</label><div className="form-actions span-2"><Link className="btn secondary" to={item ? `/reclamacoes/${item.id}` : '/reclamacoes'}>Cancelar</Link><button className="btn primary" type="submit" disabled={saving || mismatch}>{saving ? 'Salvando…' : item ? 'Salvar alterações' : 'Registrar reclamação'}</button></div></form></Panel>;
}
