import { useState } from 'react';
import { Link, NavLink, useParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { actionLabels, complaintLabels, formatDate, get, investigationLabels, isNotFound, nextAction, nextInvestigation, patch, post, put, remove, safeExternalUrl, suggestionLabels, todayLocal, type AgentAnalysis, type Complaint, type CorrectiveAction, type Evidence, type Investigation, type Suggestion, type User } from './api';
import { useAuth, useSafeMutation } from './auth';
import { Alert, Badge, DataTable, Empty, Panel, QueryState } from './ui';

const tabs = [
  ['Visão geral', ''], ['Evidências', '/evidencias'], ['Investigação', '/investigacao'],
  ['Ações corretivas', '/acoes-corretivas'], ['QualityOps AI', '/qualityops-ai'],
  ['Sugestões da IA', '/sugestoes'], ['Casos semelhantes', '/casos-semelhantes'], ['Histórico', '/historico'],
];
const evidenceSchema = z.object({ title: z.string().trim().min(1, 'Informe o título').max(150), description: z.string().max(2000), fileUrl: z.string().max(500) });
const investigationSchema = z.object({ analysis: z.string().max(3000), rootCause: z.string().max(2000) });
const actionSchema = z.object({ description: z.string().trim().min(1, 'Informe a ação').max(2000), responsibleId: z.string().min(1, 'Selecione o responsável'), dueDate: z.string().min(1, 'Informe o prazo').refine(value => value >= todayLocal(), 'O prazo deve ser hoje ou uma data futura') });
const agentSchema = z.object({ message: z.string().trim().min(1, 'Informe uma mensagem').max(1000) });
type EvidenceForm = z.infer<typeof evidenceSchema>; type InvestigationForm = z.infer<typeof investigationSchema>; type ActionForm = z.infer<typeof actionSchema>; type AgentForm = z.infer<typeof agentSchema>;

export function Workspace() {
  const { id = '', '*': section = '' } = useParams(); const { user } = useAuth();
  const complaint = useQuery({ queryKey: ['complaint', id], queryFn: () => get<Complaint>(`/complaints/${id}`) });
  const evidences = useQuery({ queryKey: ['evidences', id], queryFn: () => get<Evidence[]>(`/evidences/complaint/${id}`), enabled: !!complaint.data });
  const investigation = useQuery({ queryKey: ['investigation', id], queryFn: () => get<Investigation>(`/investigations/complaint/${id}`), enabled: !!complaint.data, retry: (count, error) => !isNotFound(error) && count < 1 });
  const actions = useQuery({ queryKey: ['actions', investigation.data?.id], queryFn: () => get<CorrectiveAction[]>(`/corrective-actions/investigation/${investigation.data!.id}`), enabled: !!investigation.data });
  const suggestions = useQuery({ queryKey: ['suggestions', id], queryFn: () => get<Suggestion[]>(`/investigation-suggestions/complaint/${id}`), enabled: !!complaint.data });
  const similar = useQuery({ queryKey: ['similar', id], queryFn: () => get<Complaint[]>(`/complaints/${id}/similar`), enabled: !!complaint.data && (user?.role === 'ADMIN' || user?.role === 'QUALITY_ANALYST') && (section === '' || section === 'casos-semelhantes'), retry: false });
  const [analysis, setAnalysis] = useState<AgentAnalysis['analysis'] | null>(null);
  const invMissing = isNotFound(investigation.error);
  const commonError = evidences.error || (invMissing ? null : investigation.error) || actions.error || suggestions.error;
  if (complaint.isLoading) return <div className="state">Carregando reclamação…</div>;
  if (complaint.error || !complaint.data) return <div className="state error">{isNotFound(complaint.error) ? 'Reclamação não encontrada.' : 'Não foi possível carregar a reclamação.'}</div>;
  const c = complaint.data; const base = `/reclamacoes/${c.id}`;
  const evidencePanel = <EvidencePanel complaintId={c.id} items={evidences.data || []} compact={section === ''} />;
  const investigationPanel = <InvestigationPanel complaintId={c.id} item={investigation.data || null} compact={section === ''} />;
  const actionPanel = <ActionsPanel investigation={investigation.data || null} items={actions.data || []} compact={section === ''} />;
  const aiPanel = <AiPanel complaintId={c.id} analysis={analysis} setAnalysis={setAnalysis} compact={section === ''} />;
  const suggestionPanel = <SuggestionsPanel complaintId={c.id} items={suggestions.data || []} compact={section === ''} />;
  const similarPanel = <SimilarPanel items={similar.data || []} error={similar.error} loading={similar.isLoading} compact={section === ''} />;
  return <><div className="workspace-heading"><div><div className="eyebrow">DETALHES DA RECLAMAÇÃO · #{c.id.slice(0, 8)}</div><h1>{c.title}</h1><p>{c.customerName} <span>·</span> {c.productName} <span>·</span> {c.lotCode || 'Sem lote'} <span>·</span> Criada em {formatDate(c.createdAt)} por {c.createdByName}</p></div><div className="status-control"><Badge tone={c.status === 'INVESTIGATING' ? 'blue' : c.status === 'UNDER_ANALYSIS' ? 'amber' : 'teal'}>{complaintLabels[c.status]}</Badge><Link className="btn secondary" to={`${base}/editar`}>Editar dados</Link><StatusButton complaint={c} /></div></div>
    <div className="stepper">{Object.entries(complaintLabels).map(([value, label], index) => <div key={value} className={`step ${index <= Object.keys(complaintLabels).indexOf(c.status) ? 'done' : ''}`}><span className="step-dot" />{label}</div>)}</div>
    <div className="tabs">{tabs.map(([label, suffix]) => <NavLink end key={suffix} to={base + suffix} className={({ isActive }) => `tab ${isActive ? 'active' : ''}`}>{label}</NavLink>)}</div>
    <QueryState loading={evidences.isLoading || investigation.isLoading || suggestions.isLoading || (!!investigation.data && actions.isLoading)} error={commonError}>
      {section === 'evidencias' ? evidencePanel : section === 'investigacao' ? investigationPanel : section === 'acoes-corretivas' ? actionPanel : section === 'qualityops-ai' ? aiPanel : section === 'sugestoes' ? suggestionPanel : section === 'casos-semelhantes' ? similarPanel : section === 'historico' ? <HistoryPanel complaint={c} /> : <><div className="workspace-grid">{evidencePanel}{investigationPanel}{actionPanel}{aiPanel}{suggestionPanel}{similarPanel}</div><div className="workspace-bottom"><Panel title="Visão geral"><div className="detail-grid"><div><small>DESCRIÇÃO</small><strong>{c.description}</strong></div><div><small>REGISTRADA POR</small><strong>{c.createdByName}</strong></div></div></Panel><HistoryPanel complaint={c} /></div></>}
    </QueryState></>;
}
function StatusButton({ complaint }: { complaint: Complaint }) { const next = ({ OPEN: 'UNDER_ANALYSIS', UNDER_ANALYSIS: 'INVESTIGATING', INVESTIGATING: 'RESOLVED', RESOLVED: 'CLOSED' } as const)[complaint.status as 'OPEN' | 'UNDER_ANALYSIS' | 'INVESTIGATING' | 'RESOLVED']; const qc = useQueryClient(); const mutation = useSafeMutation(); return <>{next && <button className="btn primary" disabled={mutation.pending} onClick={() => mutation.run(() => patch<Complaint>(`/complaints/${complaint.id}/status`, { status: next }), () => { qc.invalidateQueries({ queryKey: ['complaint', complaint.id] }); qc.invalidateQueries({ queryKey: ['complaints'] }); })}>Avançar para {complaintLabels[next]}</button>}<Alert message={mutation.error} /></>; }

function EvidencePanel({ complaintId, items, compact }: { complaintId: string; items: Evidence[]; compact: boolean }) { const { user } = useAuth(); const qc = useQueryClient(); const mutation = useSafeMutation(); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const { register, handleSubmit, reset, formState: { errors } } = useForm<EvidenceForm>({ resolver: zodResolver(evidenceSchema), defaultValues: { title: '', description: '', fileUrl: '' } });
  return <Panel title="Evidências" action={compact ? <Link className="text-link" to={`/reclamacoes/${complaintId}/evidencias`}>Abrir →</Link> : <button className="mini-btn accept" onClick={() => setEditing(true)}>+ Adicionar</button>} className={compact ? '' : 'detail-panel'}><div className="stack">{items.length ? items.map(e => <div className="subcard" key={e.id}><strong>▤ {e.title}</strong><p>{e.description || 'Sem descrição'} · {formatDate(e.createdAt)} · {e.createdByName}</p>{safeExternalUrl(e.fileUrl) && <a className="text-link" href={safeExternalUrl(e.fileUrl)!} target="_blank" rel="noopener noreferrer">Abrir URL informada ↗</a>}{!compact && user?.role === 'ADMIN' && <button className="mini-btn reject" onClick={async () => { if (!window.confirm(`Excluir evidência ${e.title}?`)) return; await mutation.run(() => remove(`/evidences/${e.id}`), () => qc.invalidateQueries({ queryKey: ['evidences', complaintId] })); }}>Excluir</button>}</div>) : <Empty text="Nenhuma evidência cadastrada." />}</div>{!compact && editing && <form className="form-grid inline-form" onSubmit={handleSubmit(async values => { setSaving(true); await mutation.run(() => post<Evidence>('/evidences', { complaintId, ...values }), () => { qc.invalidateQueries({ queryKey: ['evidences', complaintId] }); setEditing(false); reset(); }); setSaving(false); })}><label>Título<input {...register('title')} />{errors.title && <small className="error">{errors.title.message}</small>}</label><label>URL do arquivo <span className="optional">(opcional)</span><input {...register('fileUrl')} /></label><label className="span-2">Descrição<textarea rows={3} {...register('description')} /></label><div className="form-actions span-2"><button type="button" className="btn secondary" onClick={() => setEditing(false)}>Cancelar</button><button className="btn primary" disabled={saving}>Salvar evidência</button></div></form>}<Alert message={mutation.error} />{!compact && <div className="soft-note">O backend aceita uma URL; não há endpoint de upload de arquivo.</div>}</Panel>;
}

function InvestigationPanel({ complaintId, item, compact }: { complaintId: string; item: Investigation | null; compact: boolean }) { const qc = useQueryClient(); const mutation = useSafeMutation(); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const { register, handleSubmit, reset, formState: { errors } } = useForm<InvestigationForm>({ resolver: zodResolver(investigationSchema), defaultValues: { analysis: item?.analysis || '', rootCause: item?.rootCause || '' } });
  const transitions = item ? nextInvestigation[item.status] : [];
  return <Panel title="Investigação" action={compact ? <Link className="text-link" to={`/reclamacoes/${complaintId}/investigacao`}>Abrir →</Link> : item ? <Badge tone="amber">{investigationLabels[item.status]}</Badge> : undefined} className={compact ? '' : 'detail-panel'}>{item ? <><p className="panel-intro">{item.analysis || 'Análise ainda não registrada.'}</p><div className="subcard"><strong>Causa raiz — confirmação humana</strong><p>{item.rootCause || 'Ainda não confirmada pelo analista.'}</p></div><div className="meta-line">Criada por {item.createdByName} · {formatDate(item.createdAt)}</div></> : <Empty text="Nenhuma investigação iniciada." />}
    {!compact && <><div className="inline-actions top-gap">{!editing && <button className="mini-btn accept" onClick={() => { reset({ analysis: item?.analysis || '', rootCause: item?.rootCause || '' }); setEditing(true); }}>{item ? 'Editar investigação' : 'Iniciar investigação'}</button>}{item && transitions.map(status => <button className="mini-btn accept" disabled={mutation.pending} key={status} onClick={() => mutation.run(() => patch<Investigation>(`/investigations/${item.id}/status`, { status }), () => qc.invalidateQueries({ queryKey: ['investigation', complaintId] }))}>{investigationLabels[status]}</button>)}</div>{editing && <form className="form-grid inline-form" onSubmit={handleSubmit(async values => { setSaving(true); await mutation.run(() => item ? put<Investigation>(`/investigations/${item.id}`, { complaintId, ...values }) : post<Investigation>('/investigations', { complaintId, ...values }), () => { qc.invalidateQueries({ queryKey: ['investigation', complaintId] }); qc.invalidateQueries({ queryKey: ['investigations'] }); setEditing(false); }); setSaving(false); })}><label className="span-2">Análise<textarea rows={4} {...register('analysis')} />{errors.analysis && <small className="error">Máximo de 3000 caracteres.</small>}</label><label className="span-2">Causa raiz confirmada pelo analista<textarea rows={3} {...register('rootCause')} />{errors.rootCause && <small className="error">Máximo de 2000 caracteres.</small>}</label><div className="form-actions span-2"><button type="button" className="btn secondary" onClick={() => setEditing(false)}>Cancelar</button><button className="btn primary" disabled={saving}>Salvar investigação</button></div></form>}</>}<Alert message={mutation.error} /></Panel>;
}

function ActionsPanel({ investigation, items, compact }: { investigation: Investigation | null; items: CorrectiveAction[]; compact: boolean }) { const { user } = useAuth(); const qc = useQueryClient(); const mutation = useSafeMutation(); const [editing, setEditing] = useState<CorrectiveAction | 'new' | null>(null); const [saving, setSaving] = useState(false); const users = useQuery({ queryKey: ['users'], queryFn: () => get<User[]>('/users'), enabled: user?.role === 'ADMIN' && !compact });
  return <Panel title="Ações corretivas" action={compact && investigation ? <Link className="text-link" to={`/reclamacoes/${investigation.complaintId}/acoes-corretivas`}>Abrir →</Link> : <Badge>{items.length} ações</Badge>} className={compact ? '' : 'detail-panel'}>{investigation ? <><div className="stack">{items.length ? items.map(action => <div className="subcard" key={action.id}><strong>{action.description}</strong><p>{action.responsibleName} · Prazo {formatDate(action.dueDate)}</p><Badge tone={action.status === 'OVERDUE' ? 'red' : action.status === 'IN_PROGRESS' ? 'amber' : 'gray'}>{actionLabels[action.status]}</Badge>{!compact && <div className="inline-actions top-gap"><button className="mini-btn accept" onClick={() => setEditing(action)}>Editar</button>{nextAction[action.status].map(status => <button key={status} className="mini-btn accept" disabled={mutation.pending} onClick={() => mutation.run(() => patch<CorrectiveAction>(`/corrective-actions/${action.id}/status`, { status }), () => { qc.invalidateQueries({ queryKey: ['actions', investigation.id] }); qc.invalidateQueries({ queryKey: ['actions'] }); })}>{actionLabels[status]}</button>)}</div>}</div>) : <Empty text="Nenhuma ação cadastrada." />}</div>{!compact && <><button className="mini-btn accept top-gap" onClick={() => setEditing('new')}>+ Nova ação</button>{editing && <ActionEditor key={editing === 'new' ? 'new' : editing.id} item={editing === 'new' ? undefined : editing} responsibleOptions={user?.role === 'ADMIN' ? (users.data || []).filter(u => u.active).map(u => ({ id: u.id, name: u.name })) : user ? [{ id: user.id, name: `${user.name} (você)` }] : []} saving={saving} cancel={() => setEditing(null)} submit={async values => { setSaving(true); await mutation.run(() => editing === 'new' ? post<CorrectiveAction>('/corrective-actions', { investigationId: investigation.id, ...values }) : put<CorrectiveAction>(`/corrective-actions/${editing.id}`, { investigationId: investigation.id, ...values }), () => { qc.invalidateQueries({ queryKey: ['actions', investigation.id] }); qc.invalidateQueries({ queryKey: ['actions'] }); setEditing(null); }); setSaving(false); }} />}{users.error && <Alert message="Não foi possível carregar a lista de responsáveis." />}{user?.role !== 'ADMIN' && <div className="soft-note">Seu perfil pode selecionar apenas a própria conta; a listagem de usuários é restrita a ADMIN.</div>}</>}</> : <Empty text="Inicie uma investigação antes de cadastrar ações corretivas." />}<Alert message={mutation.error} /></Panel>;
}
function ActionEditor({ item, responsibleOptions, saving, cancel, submit }: { item?: CorrectiveAction; responsibleOptions: { id: string; name: string }[]; saving: boolean; cancel: () => void; submit: (data: ActionForm) => Promise<void> }) { const options = item && !responsibleOptions.some(u => u.id === item.responsibleId) ? [{ id: item.responsibleId, name: item.responsibleName }, ...responsibleOptions] : responsibleOptions; const { register, handleSubmit, formState: { errors } } = useForm<ActionForm>({ resolver: zodResolver(actionSchema), defaultValues: { description: item?.description || '', responsibleId: item?.responsibleId || options[0]?.id || '', dueDate: item?.dueDate || '' } }); return <form className="form-grid inline-form" onSubmit={handleSubmit(submit)}><label className="span-2">Descrição<textarea rows={3} {...register('description')} />{errors.description && <small className="error">{errors.description.message}</small>}</label><label>Responsável<select {...register('responsibleId')}><option value="">Selecione</option>{options.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select>{errors.responsibleId && <small className="error">{errors.responsibleId.message}</small>}</label><label>Prazo<input type="date" min={todayLocal()} {...register('dueDate')} />{errors.dueDate && <small className="error">{errors.dueDate.message}</small>}</label><div className="form-actions span-2"><button type="button" className="btn secondary" onClick={cancel}>Cancelar</button><button className="btn primary" disabled={saving}>Salvar ação</button></div></form>; }

function AiPanel({ complaintId, analysis, setAnalysis, compact }: { complaintId: string; analysis: AgentAnalysis['analysis'] | null; setAnalysis: (value: AgentAnalysis['analysis']) => void; compact: boolean }) { const mutation = useSafeMutation(); const [running, setRunning] = useState(false); const { register, handleSubmit, formState: { errors } } = useForm<AgentForm>({ resolver: zodResolver(agentSchema), defaultValues: { message: '' } });
  return <Panel title="Assistente QualityOps AI" action={compact ? <Link className="text-link" to={`/reclamacoes/${complaintId}/qualityops-ai`}>Abrir →</Link> : undefined} className={`ai-panel ${compact ? '' : 'detail-panel'}`}>
    {analysis ? <><AiList title="Hipóteses" items={analysis.hypotheses} /><AiList title="Informações faltantes" items={analysis.missingInformation} /><AiList title="Próximos passos" items={analysis.nextSteps} /></> : <Empty text="Nenhuma análise solicitada nesta sessão. A API não fornece histórico de análises para consulta." />}
    {!compact && <form className="inline-form" onSubmit={handleSubmit(async values => { setRunning(true); await mutation.run(() => post<AgentAnalysis>(`/agent/complaints/${complaintId}/investigate`, values), result => setAnalysis(result.analysis)); setRunning(false); })}><label className="field-label">Solicitação ao agente<textarea rows={3} {...register('message')} placeholder="Descreva o apoio necessário para esta reclamação" />{errors.message && <small className="error">{errors.message.message}</small>}</label><button className="btn primary top-gap" disabled={running}>{running ? 'Analisando…' : 'Analisar reclamação'}</button></form>}<Alert message={mutation.error} /><small>IA apenas assistiva: hipóteses e próximos passos exigem revisão humana. A IA não confirma causa raiz nem altera estados.</small></Panel>;
}
function AiList({ title, items }: { title: string; items: string[] }) { return <div className="ai-line"><strong>{title}</strong><span>{items.length ? items.join(' · ') : 'Nenhuma informação'}</span></div>; }

function SuggestionsPanel({ complaintId, items, compact }: { complaintId: string; items: Suggestion[]; compact: boolean }) { const qc = useQueryClient(); const mutation = useSafeMutation(); const [running, setRunning] = useState(false); const { register, handleSubmit, formState: { errors } } = useForm<AgentForm>({ resolver: zodResolver(agentSchema), defaultValues: { message: '' } });
  return <Panel title="Sugestões para revisão" action={compact ? <Link className="text-link" to={`/reclamacoes/${complaintId}/sugestoes`}>Abrir →</Link> : undefined} className={compact ? '' : 'detail-panel'}><div className="stack">{items.length ? items.map(s => <div className="subcard" key={s.id}><strong>{s.suggestion}</strong><p><Badge tone={s.status === 'PENDING' ? 'amber' : s.status === 'ACCEPTED' ? 'teal' : 'red'}>{suggestionLabels[s.status]}</Badge> · {formatDate(s.createdAt)}</p>{!compact && s.status === 'PENDING' && <div className="inline-actions"><button className="mini-btn accept" disabled={mutation.pending} onClick={() => mutation.run(() => patch<Suggestion>(`/investigation-suggestions/${s.id}/status`, { status: 'ACCEPTED' }), () => qc.invalidateQueries({ queryKey: ['suggestions', complaintId] }))}>Aceitar</button><button className="mini-btn reject" disabled={mutation.pending} onClick={() => mutation.run(() => patch<Suggestion>(`/investigation-suggestions/${s.id}/status`, { status: 'REJECTED' }), () => qc.invalidateQueries({ queryKey: ['suggestions', complaintId] }))}>Rejeitar</button></div>}</div>) : <Empty text="Nenhuma sugestão cadastrada." />}</div>{!compact && <form className="inline-form" onSubmit={handleSubmit(async values => { setRunning(true); await mutation.run(() => post<Suggestion>(`/agent/complaints/${complaintId}/suggestions`, values), () => qc.invalidateQueries({ queryKey: ['suggestions', complaintId] })); setRunning(false); })}><label className="field-label">Pedir sugestão à IA<textarea rows={3} {...register('message')} placeholder="Qual aspecto da investigação precisa de apoio?" />{errors.message && <small className="error">{errors.message.message}</small>}</label><button className="btn primary top-gap" disabled={running}>{running ? 'Gerando…' : 'Gerar sugestão'}</button></form>}<Alert message={mutation.error} /><div className="soft-note">IA sugere → analista revisa → aceita ou rejeita. A sugestão não confirma a causa raiz.</div></Panel>;
}

function SimilarPanel({ items, error, loading, compact }: { items: Complaint[]; error: unknown; loading: boolean; compact: boolean }) { return <Panel title="Casos semelhantes" className={compact ? '' : 'detail-panel'}><QueryState loading={loading} error={error}>{items.length ? items.map(c => <div className="subcard" key={c.id}><strong>Caso semanticamente semelhante: {c.title}</strong><p>{c.customerName} · {c.productName} · {c.lotCode || 'Sem lote'}</p><Link className="text-link" to={`/reclamacoes/${c.id}`}>Ver caso relacionado →</Link></div>) : <Empty text="Nenhum caso semelhante encontrado." />}</QueryState><div className="soft-note">Semelhança semântica não confirma a mesma causa raiz.</div></Panel>; }
function HistoryPanel({ complaint }: { complaint: Complaint }) { return <Panel title="Histórico e rastreabilidade"><div className="timeline"><div><span className="timeline-dot" /><strong>Registro criado</strong><p>{formatDate(complaint.createdAt)} · {complaint.createdByName}</p></div><div><span className="timeline-dot" /><strong>Última atualização conhecida</strong><p>{formatDate(complaint.updatedAt)} · Estado atual: {complaintLabels[complaint.status]}</p></div></div><div className="soft-note">O backend não oferece endpoint de eventos ou alterações históricas.</div></Panel>; }

export function InvestigationsPage() { const q = useQuery({ queryKey: ['investigations'], queryFn: () => get<Investigation[]>('/investigations') }); const [filter, setFilter] = useState(''); const items = (q.data || []).filter(i => `${i.complaintTitle} ${i.status}`.toLowerCase().includes(filter.toLowerCase())); return <><div className="page-heading"><div><div className="eyebrow">OPERAÇÃO / INVESTIGAÇÕES</div><h1>Investigações</h1><p>Análises relacionadas às reclamações</p></div></div><Panel title="Investigações registradas"><div className="filters"><input className="search" placeholder="⌕  Buscar investigação" value={filter} onChange={e => setFilter(e.target.value)} /></div><QueryState loading={q.isLoading} error={q.error}>{items.length ? <DataTable headers={['RECLAMAÇÃO', 'STATUS', 'RESPONSÁVEL', 'CRIADA']} rows={items.map(i => [<Link className="row-link" to={`/reclamacoes/${i.complaintId}/investigacao`}>{i.complaintTitle}</Link>, <Badge tone="amber">{investigationLabels[i.status]}</Badge>, i.createdByName, formatDate(i.createdAt)])} /> : <Empty text="Nenhuma investigação encontrada." />}</QueryState></Panel></>; }
export function ActionsPage() { const q = useQuery({ queryKey: ['actions'], queryFn: () => get<CorrectiveAction[]>('/corrective-actions') }); const investigations = useQuery({ queryKey: ['investigations'], queryFn: () => get<Investigation[]>('/investigations') }); const [filter, setFilter] = useState(''); const items = (q.data || []).filter(a => `${a.description} ${a.responsibleName} ${a.status}`.toLowerCase().includes(filter.toLowerCase())); return <><div className="page-heading"><div><div className="eyebrow">OPERAÇÃO / AÇÕES CORRETIVAS</div><h1>Ações corretivas</h1><p>Acompanhamento das ações registradas</p></div></div><Panel title="Ações registradas"><div className="filters"><input className="search" placeholder="⌕  Buscar ação corretiva" value={filter} onChange={e => setFilter(e.target.value)} /></div><QueryState loading={q.isLoading || investigations.isLoading} error={q.error || investigations.error}>{items.length ? <DataTable headers={['AÇÃO', 'RESPONSÁVEL', 'PRAZO', 'STATUS', 'CASO']} rows={items.map(a => { const i = investigations.data?.find(inv => inv.id === a.investigationId); return [a.description, a.responsibleName, formatDate(a.dueDate), <Badge tone={a.status === 'OVERDUE' ? 'red' : 'amber'}>{actionLabels[a.status]}</Badge>, i ? <Link className="row-link" to={`/reclamacoes/${i.complaintId}/acoes-corretivas`}>Abrir caso →</Link> : '—']; })} /> : <Empty text="Nenhuma ação encontrada." />}</QueryState></Panel></>; }
